### ISSUE TITLE
Hide Non-Grocery Lists By Default (ENHANCEMENT)

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/johnston_home_hub#5]
# By default, only the Grocery List should show, with the other lists being rendered based on a "reveal" button click
![Image](https://user-images.githubusercontent.com/12022922/183925815-e015ea4b-2265-4f60-9beb-ff59ab68169f.png)
_Pictured, redesigned `WidgetWrapper` component with `Reveal` icon and call-to-action_ 

## Subtasks
- [ ] Add `reveal` icon
- [ ] Truncate `Link` text in `Online` lists
- [ ] Update `WidgetWrapper` styled-component to conditionally render based on `isRevealed` prop
- [ ] Add local state to `App.tsx` to control `WidgetWrapper` reveal state
